### ISSUE TITLE
careers page minor styling improvements

### ISSUE THREAD

**Issue by pimato** [makerdao/makerdao.github.io#10]
- give #main-content a `padding-top: 30px`, `padding-bottom: 30px`
- give #career-list a `font-size: 1.0 em`

**Comment by matttrichards** [comment]
can you post a SS pls @pimato ?

**Comment by matttrichards** [comment]
@ferni would you mind showing us what it would look like if we align the bottom bar with the text above?

**Comment by ferni** [comment]
@matttrichards You mean if the width of the footer content be the same as the main content?

**Comment by matttrichards** [comment]
Basically the ideal situation is that it lines up on the left hand side
(rather than one aligned left and the other seemingly in the middle).

It's a low level change in any case though so if we could please just set
this live and deal with the cosmetics later that would be great.


Matt

**Comment by ferni** [comment]
@matttrichards Okay, merged.
