### ISSUE TITLE
Move https://castle.brockman.se/purple/ to makerdao.com domain

### ISSUE THREAD

**Issue by ferni** [makerdao/makerdao.github.io#4]
Issue copied from previous repo, original issue by @matttrichards
@matttrichards said:

Needs some cleaning up and formatting (font etc.) to match the look and feel of the main site. Once that is done then we replace that url with the url linked to on the home page that spawns the pdf.

**Comment by ferni** [comment]
@kennyrowe said:

I think we should just iframe it since it's still in active development

**Comment by ferni** [comment]
@matttrichards said:

sounds good

**Comment by nmushegian** [comment]
> I think we should just iframe it since it's still in active development

we don't have to do such black magic...

@mbrock

**Comment by mbrock** [comment]
The purple paper HTML is now at https://makerdao.com/purple with some slight improvements.

**Comment by matttrichards** [comment]
Can you guys put this on the repo? There is a lot that needs to be updated to create continuity with the site (font/ background/ header/footer, etc)

**Comment by dbrock** [comment]
There is no need for continuity with the site

**Comment by dbrock** [comment]
There is no need to have a consistent look and feel for everything related to MAKER DAO

**Comment by dbrock** [comment]
Let a thousand flowers bloom

**Comment by matttrichards** [comment]
@dbrock 

I took this position to build Maker as a brand. A big part of that brand development is ensuring continuity. Having continuity within a brand ensures a number of things which build a foundation upon which we can then grow Maker as a brand for the long term. You can read about them [here](https://getquestblog.wordpress.com/2011/09/14/continuity-and-consistency-in-marketing-and-advertising%E2%80%A6/), [here](https://www.b2bmarketing.net/en-gb/resources/blog/importance-brand-continuity) or [here](https://www.thebalance.com/brand-continuity-creating-an-image-greater-than-the-parts-2295179). 

I can understand how having a unified brand presence might not seem necessary at this stage... but once we open source our code and competitors with a business focus start showing up quickly after... we will be grateful we started early.
